Document: video-dl
Title: Debian video-dl Manual
Author: <insert document author here>
Abstract: This manual describes what video-dl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/video-dl/video-dl.sgml.gz

Format: postscript
Files: /usr/share/doc/video-dl/video-dl.ps.gz

Format: text
Files: /usr/share/doc/video-dl/video-dl.text.gz

Format: HTML
Index: /usr/share/doc/video-dl/html/index.html
Files: /usr/share/doc/video-dl/html/*.html
