.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "October 2015" "" ""
Video download project\.
.
.P
 \fIhttps://travis\-ci\.org/danog/video\-dl\fR
.
.P
Read in Italian \fIhttps://github\.com/danog/video\-dl/blob/master/README\-IT\.md\fR
.
.P
Created by Daniil Gentili \fIhttp://daniil\.it\fR\.
.
.P
This project is licensed under the terms of the GPLv3 license\.
.
.P
The programs included in this project can be used to download videos from any generic site including the Italian Rai \fIhttp://rai\.tv\fR Television website (including rai replay and iframe videos), the italian Mediaset \fIhttp://mediaset\.it\fR website (including iframes like the ones on the Witty TV \fIhttp://wittytv\.it\fR website), and the LA7 \fIhttp://la7\.it\fR website\. And thanks to youtube\-dl now they support lots of other websites!
.
.P
This project features a Bash script that can be installed on \fIany Linux/Unix system\fR including \fIAndroid\fR, \fIMac OS X\fR or \fIiOS\fR and even on \fIWindows\fR, an \fIAPI\fR, an \fIAndroid app\fR and even a \fIweb version\fR!
.
.P
Both the \fIAPI\fR and the \fIweb version\fR use a database \fIhttps://github\.com/danog/video\-dl/blob/master/web/video_db\.sql\fR\.
.
.SH "Web version"
This project also features a web version \fIhttps://video\.daniil\.it/\fR\.
.
.P
.
.P
The source code of the page can be viewed here \fIhttps://github\.com/danog/video\-dl/blob/master/web\fR\.
.
.SH "Bash script usage:"
.
.nf


video\.sh [ \-qaf [ urls\.txt ] ] URL URL2 URL3 \.\.\.

Do not forget to put the URL between quotes if it contains special chars like & or #\.

Run with \./video\.sh if you installed in a directory not in $PATH\.

Options:




\-q              Quiet mode: useful for crontab jobs, automatically enables \-a\.

\-a              Automatic mode: automatically download the video in the maximum quality\.

\-b              Use built\-in API engine: requires additional programs and may not work properly on some systems but may be faster than the API server\.

\-f              Read URL(s) from specified text file(s)\. If specified, you cannot provide URLs as arguments\.

\-p=player       Play the video instead of downloading it using specified player, mplayer if none specified\.

\-\-help          Show this extremely helpful message\.
.
.fi
.
.SS "Bash script installation instructions:"
.
.P
On debian\-derived distros, execute this command to add my repo to your system:
.
.IP "" 4
.
.nf

sudo wget \-q \-O /etc/apt/sources\.list\.d/daniil\.list http://dano\.cu\.cc/1IJrcd1 && wget \-q \-O \- http://dano\.cu\.cc/1Aci9Qp | sudo apt\-key add \- && sudo apt\-key adv \-\-recv\-keys \-\-keyserver keys\.gnupg\.net 72B97FD1D9672C93 && sudo apt\-get update
.
.fi
.
.IP "" 0
.
.P
You should see an OK if the operation was successful\.
.
.P
And this command to install the script\.
.
.IP "" 4
.
.nf

sudo apt\-get update; sudo apt\-get \-y install video\-dl
.
.fi
.
.IP "" 0
.
.P
Execute this command to install the script:
.
.IP "" 4
.
.nf

wget http://daniilgentili\.magix\.net/video\.sh \-O video\.sh || curl \-L http://daniilgentili\.magix\.net/video\.sh \-o video\.sh; chmod +x video\.sh
.
.fi
.
.IP "" 0
.
.P
Run with \./video\.sh in the directory where you downloaded it\.
.
.P
To use from any directory install the script directly in the $PATH using this command (run as root):
.
.IP "" 4
.
.nf

wget http://daniilgentili\.magix\.net/video\.sh \-O /usr/bin/video\.sh || curl \-L http://daniilgentili\.magix\.net/video\.sh \-o video\.sh; chmod +x /usr/bin/video\.sh
.
.fi
.
.IP "" 0
.
.P
Enable unknown sources and install this app \fIhttp://bit\.ly/0192837465k\fR\. Once opened you will be presented with a user friendly interface similar to the web version\.
.
.P
1: initial version
.
.P
1\.2: added not working, share and credits button
.
.P
1\.2\.1: added external sharing option, fixed bugs
.
.P
1\.2\.2: Fixed not working button on external share URL, added google analytics, fixed Rai Replay on external share\.
.
.P
1\.3: Added auto update\.
.
.P
1\.4: Added more credits\.
.
.P
You tell me!
.
.P
Video tutorial \fIhttps://www\.youtube\.com/watch?v=4NLs2NzHbbc\fR
.
.P
Note: if you can\'t copy & paste the commands directly in the Terminal Emulator app try this: paste them in the url bar one line at a time, copy them again from the url bar and try to paste them again in the Terminal Emulator app\. Run these commands: \fBcd /sdcard && wget http://daniilgentili\.magix\.net/android/video\.sh\fR
.
.P
Run with: \fBbash /sdcard/video\.sh\fR
.
.P
To install the script directly in the $PATH use these commands (here, root is mandatory)\.
.
.IP "" 4
.
.nf

su
mount \-o rw,remount /system && wget http://daniilgentili\.magix\.net/android/video\.sh \-O /system/bin/video\.sh && chmod 755 /system/bin/video\.sh
.
.fi
.
.IP "" 0
.
.P
If you cannot execute the script match the its shebang (the #!) to the location of the bash executable\.
.
.SS "iOS:"
Jailbreak your device, install mobileterminal, sed and wget and run the following command:
.
.IP "" 4
.
.nf

wget http://daniilgentili\.magix\.net/video\.sh \-O video\.sh || curl \-L http://daniilgentili\.magix\.net/video\.sh \-o video\.sh; chmod +x video\.sh
.
.fi
.
.IP "" 0
.
.P
Run with \./video\.sh In the directory where you downloaded it\.
.
.P
To view and import the downloaded video to the gallery use iFile or Filza\.
.
.P
To use from any directory install the script directly in $PATH using this command:
.
.IP "" 4
.
.nf

su \-c "wget http://daniilgentili\.magix\.net/video\.sh \-O /usr/bin/video\.sh || curl \-L http://daniilgentili\.magix\.net/video\.sh \-o video\.sh; chmod +x /usr/bin/video\.sh"
.
.fi
.
.IP "" 0
.
.SS "Windows:"
Install Cygwin \fIhttps://www\.cygwin\.com\fR (don\'t forget to install wget and sed during the installation process!), open its command prompt and type:
.
.IP "" 4
.
.nf

wget http://daniilgentili\.magix\.net/win/video\.sh \-O video\.sh
.
.fi
.
.IP "" 0
.
.P
Run with \./video\.sh In the directory where you downloaded it\.
.
.P
To run the script from any directory run the following commands:
.
.IP "" 4
.
.nf

cd /bin && wget http://daniilgentili\.magix\.net/win/video\.sh \-O video\.sh && cd $OLDPWD
.
.fi
.
.IP "" 0
.
.SH "API"
This project also features an API \fIhttp://video\.daniil\.it/api/\fR\.
.
.P
The source code of the API can be viewed here \fIhttps://github\.com/danog/video\-dl/blob/master/api\fR\.
.
.P
The API supports GET requests and the endpoint is http://api\.daniil\.it (supports https)\.
.
.SS "Supported parameters:"
.
.P
The value should be the URL of the video to download\. The response will be a list of URLS with the corresponding quality name, format, size and dimension\.
.
.P
Example:
.
.IP "" 4
.
.nf

http://api\.daniil\.it/?url=http://www\.winx\.rai\.it/dl/RaiTV/programmi/media/ContentItem\-47307196\-8fd1\-46f8\-8b31\-92ae5f9b5089\.html#p=0
.
.fi
.
.IP "" 0
.
.P
Output:
.
.IP "" 4
.
.nf

Winx_Club_VI_Ep3_Il_collegio_volante Winx Club VI \- Ep\.3: Il collegio volante
Highest quality (mp4, 286MB, 1024x576) http://creativemedia4\.rai\.it/Italy/podcastcdn/junior/Winx/Winx_6_puntate/2189463_1800\.mp4
Medium\-low quality (mp4, 131MB, 700x394) http://creativemedia4\.rai\.it/Italy/podcastcdn/junior/Winx/Winx_6_puntate/2189463_800\.mp4
.
.fi
.
.IP "" 0
.
.P
Explanation:
.
.IP "" 4
.
.nf

Winx_Club_VI_Ep3_Il_collegio_volante Winx Club VI \- Ep\.3: Il collegio volante
.
.fi
.
.IP "" 0
.
.P
Sanitized name of video for file name Original name of the video for printing to user output
.
.IP "" 4
.
.nf

Highest quality (mp4, 286MB, 1024x576) http://creativemedia4\.rai\.it/Italy/podcastcdn/junior/Winx/Winx_6_puntate/2189463_1800\.mp4
.
.fi
.
.IP "" 0
.
.P
Quality name (format, size, dimension) URL of the video
.
.IP "" 4
.
.nf

Medium\-low quality (mp4, 131MB, 700x394) http://creativemedia4\.rai\.it/Italy/podcastcdn/junior/Winx/Winx_6_puntate/2189463_800\.mp4
.
.fi
.
.IP "" 0
.
.P
Quality name (format, size, dimension) URL of the video
.
.P
The qualities are ordered in decreasing order by dimension\.
.
.P
Supports the following values:
.
.IP "" 4
.
.nf

websites
.
.fi
.
.IP "" 0
.
.P
returns a shortened list of supported websites:
.
.IP "" 4
.
.nf

allwebsites
.
.fi
.
.IP "" 0
.
.P
returns a full list of supported websites\.
.
.SH "Contribute!"
If you created a version of the script using another programming language contact me \fIhttp://daniil\.it\fR and I will put it on this page!
.
.P
That\'s it!
.
.P
Enjoy!
.
.P
Daniil Gentili \fIhttp://daniil\.it\fR
