#!/usr/bin/env bash
[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && {
# Setup everything 
desc="$(git log -1 --pretty=%B)"
sudo apt-get update
sudo apt-get install busybox ruby-ronn build-essential devscripts lintian diff patch patchutils dpkg-dev ruby-rdiscount
gpg --import s.key

echo '#!/usr/bin/expect -f
set timeout 2
set passphrase "'${gpg}'"
spawn dpkg-buildpackage -Zgzip -kC5C1D8BA [lindex $argv 0] [lindex $argv 1] [lindex $argv 2] [lindex $argv 3]
expect {
 "*passphrase:*" {
  send -- "$passphrase\r"
  }
} expect {
 "*passphrase:*" {
  send -- "$passphrase\r"
  }
} 
interact
'>../builddeb
builddeb="$PWD/../builddeb"
chmod +x ${builddeb}


mkdir temp
temp="$PWD/temp"
gitsync() {
branch="${1}"
shift

git add -A
git commit -am "${*}"
git push origin ${branch}

}

git clone https://${GH_TOKEN}@github.com/danog/video-dl.git video-dl
cd video-dl
git config --global user.name "${GIT_NAME}"
git config --global user.email "${GIT_EMAIL}"
git config --global push.default simple
video="$PWD"

echo "$desc" | grep -q madebytravisci && exit 1
########################################
version=$(git describe --tags)

# Sync API
cd api
sed '/api[(][)]/,/beginning of common section/!d;/echo \"\$userinput/,/video-db\.txt/d' api.sh>script_api.sh
cat $video/travis/last_api.sh >> script_api.sh
busybox ftpput -u $u2 -p $p2 $ftp api.sh script_api.sh
mv script_api.sh $video
cd $video

sed '/\#\!\/bin\/bash/,/\# 1st part ends here/!d' video.sh>tmpvideo.sh
cat script_api.sh >>tmpvideo.sh
sed '/\# 2nd part starts here/,/exit \$\?/!d' video.sh>>tmpvideo.sh
mv tmpvideo.sh video.sh
rm script_api.sh
cp video.sh $temp
cd $temp
busybox ftpput -u $u1 -p $p1 $ftp video.sh
busybox ftpput -u $u1 -p $p1 $ftp rai.sh video.sh
busybox ftpput -u $u1 -p $p1 $ftp mediaset.sh video.sh
sed 's/#!\/bin\/bash/#!\/system\/xbin\/bash/' video.sh | sed 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/android\/video.sh/' >videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/video.sh videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/rai.sh videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/mediaset.sh videoa.sh

sed 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/android\/video.sh/;s/wget/wget.exe/g;s/curl/curl.exe/g' video.sh >videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/video.sh videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/rai.sh videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/mediaset.sh videow.sh


sed -i 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/win\/video.sh/' video.sh
busybox ftpput -u $u1 -p $p1 $ftp win/video.sh video.sh
busybox ftpput -u $u1 -p $p1 $ftp win/rai.sh video.sh
busybox ftpput -u $u1 -p $p1 $ftp win/mediaset.sh video.sh

cd $video

# Generate deb
git status | grep -q video.sh && {
cd debian/*/
ronn --roff $video/README-IT.md
ronn --roff $video/README.md
mv README-IT debian/video-dl-it.1
mv README debian/video-dl.1
cp $video/video.sh video-dl/
echo "debian/video-dl.1
debian/video-dl-it.1" > debian/video-dl.manpages
dch -v $version $desc 
builddeb
: "cd $temp
git clone https://${GH_TOKEN}@github.com/danog/repo.git
cd repo/debs
cp $video/debian/*.deb .
gitsync master Updated video-dl"
cd $video
}

# Generate website
cd $video/jekyll
echo "---
layout: default
---
">index.md
sed 's/https\:\/\/github\.com\/danog\/video-dl\/blob\/master\/README-IT\.md/http\:\/\/daniil\.it\/video-dl\/it\.html/' $video/README.md >> index.md

echo "---
layout: default
---
">it.md
sed 's/https\:\/\/github\.com\/danog\/video-dl\/blob\/master\/README\.md/http\:\/\/daniil\.it\/video-dl/' $video/README.md >> it.md
cp -a * $temp
cd $video

gitsync master OK madebytravisci

# Upload everything
git checkout gh-pages
rm -rf *
cp -a $temp/* .

echo "branches:
  except:
    - gh-pages" > .travis.yml
gitsync gh-pages "Updated the website"

}
