#!/usr/bin/env bash
[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && {
# Setup everything 
desc="$(git log -1 --pretty=%B)"
echo "$desc" | grep -q madebytravisci && exit

export DEBFULLNAME="Daniil Gentili"
(
curl -sL https://deb.nodesource.com/setup | sudo bash - 

sudo apt-get update
sudo apt-get install busybox ruby-ronn build-essential devscripts lintian patch python-pip python3 patchutils gnupg expect dpkg-dev nodejs -y 
sudo npm i npm -g
sudo npm install uglify-js -g
sudo pip install pexpect
tar -xzf enc.tar.gz
gpg --allow-secret-key-import --import mygpgkey_sec.gpg
npm login << EOF
$nlogin
$npass
$nemail

EOF
) >/dev/null
builddeb="$PWD/builddeb"
chmod +x ${builddeb}

mkdir temp
temp="$PWD/temp"
gitsync() {
branch="${1}"
shift


git add -A
git commit -am "${*}"
git push -q origin ${branch}

}

git clone https://${GH_TOKEN}@github.com/danog/video-dl.git video-dl
cd video-dl
git config --global user.name "${GIT_NAME}"
git config --global user.email "${GIT_EMAIL}"
git config --global push.default simple
video="$PWD"
wget http://daniilgentili.magix.net/video.sh -O $temp/reallyold.sh
########################################
version="$(git describe --tags | sed 's/-.*//').$(git describe --tags | sed 's/-[^-]*$//;s/.*-//')"

# Sync API
cd api
sed '/api[(][)]/,/beginning of common section/!d;/echo \"\$userinput/,/video-db\.txt/d;s/exit/continue/g' api.sh>script_api.sh
cat $video/travis/last_api.sh >> script_api.sh
busybox ftpput -u $u2 -p $p2 $ftp api.sh script_api.sh
mv script_api.sh $video
cd $video

sed '/\#\!\/bin\/bash/,/\# 1st part ends here/!d' video.sh>tmpvideo.sh
cat script_api.sh >>tmpvideo.sh
sed '/\# 2nd part starts here/,/exit \$\?/!d' video.sh>>tmpvideo.sh
echo '[ "$play" != "y" ] && { echo "Downloading videos..." && eval "$queue" && echo "All downloads completed successfully." || echo "An error occurred";exit 1; } 
[ "$play" = "y" ] && { eval $queue || echo "An error occurred";exit 1; }


exit $?
'>>tmpvideo.sh

mv tmpvideo.sh video.sh
rm script_api.sh
cp video.sh $temp
cd $temp
busybox ftpput -u $u1 -p $p1 $ftp video.sh
busybox ftpput -u $u1 -p $p1 $ftp rai.sh video.sh
busybox ftpput -u $u1 -p $p1 $ftp mediaset.sh video.sh
sed 's/#!\/bin\/bash/#!\/system\/xbin\/bash/' video.sh | sed 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/android\/video.sh/' >videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/video.sh videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/rai.sh videoa.sh
busybox ftpput -u $u1 -p $p1 $ftp android/mediaset.sh videoa.sh

sed 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/android\/video.sh/;s/wget/wget.exe/g;s/curl/curl.exe/g' video.sh >videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/video.sh videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/rai.sh videow.sh
busybox ftpput -u $u1 -p $p1 $ftp win-native/mediaset.sh videow.sh


sed 's/http:\/\/daniilgentili.magix.net\/video.sh/http:\/\/daniilgentili.magix.net\/win\/video.sh/' video.sh > videoww.sh
busybox ftpput -u $u1 -p $p1 $ftp win/video.sh videoww.sh
busybox ftpput -u $u1 -p $p1 $ftp win/rai.sh videoww.sh
busybox ftpput -u $u1 -p $p1 $ftp win/mediaset.sh videoww.sh

cd $video
cp -a web $temp
# Generate deb
echo "$desc" | grep -q trigger || [ "$(diff $temp/reallyold.sh $video/video.sh)" != "" ] && {
sed -i 's/^\# Video download script v.*/\# Video download script v'$version'/g;s/echo \"Video download script v.*/echo "Video download script v'$version'/g' video.sh
cd debian/
cp * old
rm *
cd video*
cp $video/README-IT.md $video/README.md .
bundle exec ronn --roff README.md
bundle exec ronn --roff README-IT.md
mv README-IT debian/video-dl-it.1
mv README debian/video-dl.1
rm *md
cp $video/video.sh video-dl/
echo "debian/video-dl.1
debian/video-dl-it.1" > debian/video-dl.manpages
dch -v $version -D lenny --force-distribution $desc 
$builddeb
cd $temp
git clone https://${GH_TOKEN}@github.com/danog/repo.git
cd repo/debs
mkdir video-dl-$version
cd video-dl-$version
cp $video/debian/* .
gitsync master Updated video-dl to $version
cd $video
}

# Copy js

uglifyjs web/js/{video-dl.js,jquery.js,he.js,linkify.min.js,linkify-jquery.min.js} -o $temp/video-dl.min.js

[ "$(diff $video/web/js/video-dl.js $video/jquery/video-dl.js)" != "" ] && {
cp $video/web/js/video-dl.js $video/jquery/video-dl.js
cd $video/jquery
sed -i 's/"version": ".*",/"version": "'$version'",/g' package.json
npm publish
}

# Generate website
cd $video/jekyll
echo "---
layout: default
---
">index.md
sed 's/https\:\/\/github\.com\/danog\/video-dl\/blob\/master\/README-IT\.md/http\:\/\/daniil\.it\/video-dl\/it\.html/' $video/README.md >> index.md

echo "---
layout: default
---
">it.md
sed 's/https\:\/\/github\.com\/danog\/video-dl\/blob\/master\/README\.md/http\:\/\/daniil\.it\/video-dl/' $video/README-IT.md >> it.md
cp -a * $temp
mkdir $temp/repo
cd $video
gitsync master OK madebytravisci

# Upload everything
git checkout --orphan gh-pages
rm -rf *
git rm -rf * &>/dev/null
cp -a $temp/* .

echo "[submodule \"video-dl\"]
        path = repo
        url = https://github.com/danog/video-dl.git
">.gitmodules
echo "branches:
  except:
    - gh-pages" > .travis.yml

git add -A
git commit -am "Updated the website"
git push -qf origin gh-pages

}
